name: budget_app
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.4+5

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  fpdart: ^1.1.0
  image_picker: ^1.0.7
  intl: ^0.19.0
  cloud_firestore: ^4.17.3
  flutter_svg: ^2.0.10+1
  firebase_core: ^2.31.0
  firebase_storage: ^11.7.5
  firebase_auth: ^4.19.5
  collection: ^1.18.0
  cached_network_image: ^3.3.1
  font_awesome_flutter: ^10.7.0
  lottie: ^3.1.1
  get_time_ago: ^1.3.1
  month_picker_dialog: ^3.0.0
  intl_phone_number_input: ^0.7.4
  faker: ^2.1.0
  riverpod_annotation: ^2.3.5
  flutter_riverpod: ^2.5.1
  uuid: ^4.4.0
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.0.0
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  custom_lint: ^0.6.4
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.13.1

fonts:
    - family: PublicSans
      fonts:
        - asset: assets/fonts/PublicSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/PublicSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PublicSans-Medium.ttf
          weight: 500
        - asset: assets/fontsPublicSans-Regular.ttf
          weight: 400

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/svgs/
    - assets/lottie/
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"
  