name: budget_app
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  fpdart: ^1.1.0
  flutter_riverpod: ^2.4.10
  image_picker: ^1.0.7
  intl: ^0.19.0
  cloud_firestore: ^4.15.7
  flutter_svg: ^2.0.10+1
  firebase_core: ^2.26.0
  firebase_storage: ^11.6.8
  firebase_auth: ^4.17.7
  collection: ^1.18.0
  cached_network_image: ^3.3.1
  font_awesome_flutter: ^10.7.0
  lottie: ^3.1.0
  get_time_ago: ^1.3.1
  intl_phone_number_input: ^0.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

fonts:
    - family: PublicSans
      fonts:
        - asset: assets/fonts/PublicSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/PublicSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PublicSans-Medium.ttf
          weight: 500
        - asset: assets/fontsPublicSans-Regular.ttf
          weight: 400

flutter:
  uses-material-design: true
  assets:
    - assets/svgs/
    - assets/lottie/
    - assets/images/