name: budget_app
description: "A new Flutter project."

publish_to: "none"
version: 1.0.4+5

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  fpdart: ^1.1.0
  image_picker: ^1.0.7
  intl: ^0.19.0
  cloud_firestore: ^5.6.7
  flutter_svg: ^2.0.10+1
  firebase_core: ^3.13.0
  firebase_storage: ^12.4.5
  firebase_auth: ^5.5.3
  collection: ^1.18.0
  cached_network_image: ^3.3.1
  font_awesome_flutter: ^10.7.0
  lottie: ^3.1.1
  get_time_ago: ^2.3.0
  month_picker_dialog: ^6.0.3
  intl_phone_number_input: ^0.7.4
  flutter_riverpod: ^2.5.1
  uuid: ^4.4.0
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.0.0
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.3
  fl_chart: ^1.0.0
  syncfusion_flutter_xlsio: ^28.2.12
  permission_handler: ^12.0.0+1
  path_provider: ^2.1.4
  open_file: ^3.5.10
  device_info_plus: ^11.4.0
  firebase_remote_config: ^5.4.3
  firebase_crashlytics: ^4.3.5
  package_info_plus: ^8.0.2
  url_launcher: ^6.3.0
  animated_text_kit: ^4.2.2
  flutter_markdown: ^0.7.3+2
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.1.0
  google_mobile_ads: ^6.0.0
  sqflite: ^2.4.2
  path: ^1.9.1
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  custom_lint: ^0.7.5
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.14.3

fonts:
  - family: Inter
    fonts:
      - asset: assets/fonts/Inter-ExtraBold.ttf
        weight: 900
      - asset: assets/fonts/Inter-Bold.ttf
        weight: 700
      - asset: assets/fonts/Inter-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Inter-Medium.ttf
        weight: 500
      - asset: assets/fonts/Inter-Regular.ttf
        weight: 400

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/svgs/
    - assets/lottie/
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"

flutter_gen:
  synthetic-package: fal

