// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8OtTSNqQplHUYUOl9RKvxdANsfUzgQnM',
    appId: '1:79455569094:web:104b3ee25b8b69dd8643c7',
    messagingSenderId: '79455569094',
    projectId: 'budget-ss',
    authDomain: 'budget-ss.firebaseapp.com',
    storageBucket: 'budget-ss.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBf35WTLVC6chSowshmne23vRVdxGHbAQ',
    appId: '1:79455569094:android:a48a2488a696f0138643c7',
    messagingSenderId: '79455569094',
    projectId: 'budget-ss',
    storageBucket: 'budget-ss.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDthASfB3FYm95XO6IFZNfidpnNJRMUi_Q',
    appId: '1:79455569094:ios:c62570e24eb2a6288643c7',
    messagingSenderId: '79455569094',
    projectId: 'budget-ss',
    storageBucket: 'budget-ss.appspot.com',
    androidClientId:
        '79455569094-ufdkksi1h0el6aoi1fbfh0eok3744lvu.apps.googleusercontent.com',
    iosClientId:
        '79455569094-bjp0n8njj02v9esqhq0dmhtd1upntjk3.apps.googleusercontent.com',
    iosBundleId: 'com.NguyenLoi.BudgetSS',
  );
}
