// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFeLArBOmiiG9wg-ab3dFSTtUwgm2Rs2Q',
    appId: '1:609396856381:web:ac1482cb7e25f253697c54',
    messagingSenderId: '609396856381',
    projectId: 'budget-beta-2f3a5',
    authDomain: 'budget-beta-2f3a5.firebaseapp.com',
    storageBucket: 'budget-beta-2f3a5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW81xUQxlNyQu0skfNXhGIT5tUK1hynd4',
    appId: '1:609396856381:android:7062fd66e106769a697c54',
    messagingSenderId: '609396856381',
    projectId: 'budget-beta-2f3a5',
    storageBucket: 'budget-beta-2f3a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVUJ9EaSQ2w7Y0eXh6NjJEgOnmn-VBTwM',
    appId: '1:609396856381:ios:864ce6cf9aec7db7697c54',
    messagingSenderId: '609396856381',
    projectId: 'budget-beta-2f3a5',
    storageBucket: 'budget-beta-2f3a5.appspot.com',
    androidClientId: '609396856381-bgqt3k5suu3urnb3jme0b49q1sok8ror.apps.googleusercontent.com',
    iosClientId: '609396856381-ur003arvfi75e8gkcdpvfn78lh34j1qk.apps.googleusercontent.com',
    iosBundleId: 'com.NguyenLoi.BudgetSS',
  );

}