// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArjyNEvxS_39-ygzfNj4WS2vwRLeG1i8o',
    appId: '1:856201938981:web:5b9b082cbdfdabb18897cc',
    messagingSenderId: '856201938981',
    projectId: 'budget-app-5b1bb',
    authDomain: 'budget-app-5b1bb.firebaseapp.com',
    storageBucket: 'budget-app-5b1bb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPIuIgB3oda5hyF4PXov2W58MbUFpv7BY',
    appId: '1:856201938981:android:aa4af5b157d706088897cc',
    messagingSenderId: '856201938981',
    projectId: 'budget-app-5b1bb',
    storageBucket: 'budget-app-5b1bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTQSq0LIyGHQagFQimnssJoiLQ4sM-aAk',
    appId: '1:856201938981:ios:bb4ab522af202b6e8897cc',
    messagingSenderId: '856201938981',
    projectId: 'budget-app-5b1bb',
    storageBucket: 'budget-app-5b1bb.appspot.com',
    iosBundleId: 'com.example.budgetApp',
  );
}
