
default_platform(:android)

require 'ostruct'

platform :android do
  desc "Deploy a new version to the Google Play"
  lane :deploy do |options|
    begin
      mode_distribute = "internal" # "internal", "alpha", "beta", "production"
      version_code = current_version_code
      version_name = current_version

      # gradle(
      #   task: 'bundle',
      #   build_type: 'Release',
      #   flags: '--stacktrace'
      # )
      
      upload_to_play_store(
        track: mode_distribute, 
        skip_upload_changelogs: false,
        skip_upload_metadata: true,
        aab: '../build/app/outputs/bundle/release/app-release.aab',
        version_code: version_code,
        version_name: version_name
      )

      push_git_tag(version_name, version_code)
    rescue => e
      UI.error("An error occurred: #{e.message}")
      raise e
    end
  end
end

def current_version
  path = '../app/build.gradle'
  re = /versionName\s+"([^"]+)"/
  s = File.read(path)
  versionName = s[re, 1]
  return versionName
end

def current_version_code
  path = '../app/build.gradle'
  re = /versionCode\s+(\d+)/
  s = File.read(path)
  s[re, 1].to_i
end

def push_git_tag(version_name, version_code)
  add_git_tag(
    tag: "GooglePlay_#{version_name}(#{version_code})"
  )
  push_to_git_remote
end