
default_platform(:android)

require 'ostruct'

platform :android do

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    mode_distribute = "alpha"

    # find latest version code
    def latest_google_play_version_code
      tracks = ["internal", "alpha", "beta", "production"]
      version_codes = []
      tracks.each do | track |
          begin
        vc = google_play_track_version_codes(track: track)
      rescue
      puts "No track found for " + track
      else
        version_codes.concat(vc)
      end
      end
      version_codes.max || 0
    end

    # Auto increment build number
    increment_version_code(
      version_code: latest_google_play_version_code + 1
    )

    gradle(
      task: 'bundle',
      build_type: 'Release',
      flags: '--stacktrace' # Add --stacktrace option to provide more detailed error information
    )
    upload_to_play_store(
      track: mode_distribute, 
      skip_upload_changelogs: true,
      skip_upload_metadata: true,
      aab: '../build/app/outputs/bundle/release/app-release.aab',
    )
  end
end
